### PR TITLE
allow any keywords in strict mode when no allowed keys defined

### LINKED ISSUE #5: Allow any argument like `**kwarg`
In dpdispatcher, `env` argument allows any sub-arguments. We may consider to add a new class like `AnyArgument` to handle this situation.

### PR DESCRIPTION
**Pull request by njzjz**
Fix #5.

### CODE REVIEW

**Comment by njzjz** [comment]
@y1xiaoc do you think this is OK?

**Comment by y1xiaoc** [comment]
Should be good. Merged.

**Comment by njzjz** [comment]
Can you publish a new version?

**Comment by y1xiaoc** [comment]
done

**Pull request merged**
