### PR TITLE
add Sphinx directive

### LINKED ISSUE #11: [new feature] develop sphinx extension
I was just inspired by [sphinx-argparse](https://github.com/ashb/sphinx-argparse/). This extension adds a directive to sphinx as below, so we don't need to manually generate docs.
```
.. argparse::
   :module: my.module
   :func: my_func_that_returns_a_parser
   :prog: fancytool
```

We may consider adding a similar directive:
```
.. dargs::
   :module: my.module
   :func: my_func_that_returns_a_argument
```

### PR DESCRIPTION
**Pull request by njzjz**
Resolves #11.

### CODE REVIEW

**Comment by njzjz** [comment]
@y1xiaoc, ready to review.

**Comment by y1xiaoc** [comment]
Nice job! merged.

**Comment by y1xiaoc** [comment]
@njzjz do you need a new release for this PR?

**Comment by njzjz** [comment]
> @njzjz do you need a new release for this PR?

Yes of course.

**Pull request merged**
